service: route-request

plugins:
  - serverless-webpack
  # - serverless-plugin-typescript
  - serverless-offline
  - serverless-apigw-binary
  - serverless-content-encoding

custom:
  webpack:
    webpackConfig: webpack.config.ts
    packager: yarn
    includeModules:
      forceExclude:
        - 'aws-sdk'
  apigwBinary:
    types:
      - '*/*'
  contentEncoding:
    minimumCompressionSize: 0

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'development'}
  region: us-east-1
  environment:
    NODE_ENV: ${env:NODE_ENV, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - elasticbeanstalk:Describe*
        - apigateway:GET
        - apigateway:HEAD
      Resource: "*"

functions:
  serveApi:
    memorySize: 1024
    timeout: 5
    handler: src/serveApi.serveApi
    events:
      - http:
          method: ANY
          path: /{proxy+}

package:
  individually: true
  include:
    - src/**
  exclude:
    - .webpack

