service: api

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-apigw-binary
  - serverless-content-encoding

custom:
  webpack:
    webpackConfig: webpack.config.ts
    packager: yarn
    includeModules:
      forceExclude:
        - 'aws-sdk'
      forceInclude:
        - mysql
  apigwBinary:
    types:
      - '*/*'
  contentEncoding:
    minimumCompressionSize: 0

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'development'}
  region: us-east-1
  environment:
    NODE_ENV: ${env:NODE_ENV, self:provider.stage}
    TYPEORM_DATABASE: ${file(./secrets/db.${self:provider.stage}.json):database, 'hollowverse'}
    TYPEORM_HOST: ${file(./secrets/db.${self:provider.stage}.json):host, 'localhost'}
    TYPEORM_PORT: ${file(./secrets/db.${self:provider.stage}.json):port, '3306'}
    TYPEORM_USERNAME: ${file(./secrets/db.${self:provider.stage}.json):username, 'root'}
    TYPEORM_PASSWORD: ${file(./secrets/db.${self:provider.stage}.json):password, '123456'}
    FB_APP_ID: ${file(./secrets/facebookApp.json):id}
    FB_APP_ACCESS_TOKEN: ${file(./secrets/facebookApp.json):accessToken}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - elasticbeanstalk:Describe*
        - apigateway:GET
        - apigateway:HEAD
      Resource: "*"

functions:
  serveApi:
    memorySize: 1024
    timeout: 60
    handler: src/serveApi.serveApi
    vpc:
      securityGroupIds:
        - sg-f19e9ab8
      subnetIds:
        - subnet-e558a482
        - subnet-40678a1c
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{proxy+}

package:
  individually: true
  include:
    - src/**
  exclude:
    - .webpack

